name: huaman_sem06
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_database: ^10.5.7
  intl: ^0.19.0
  provider: ^6.0.5
  firebase_auth: ^4.6.0
  firebase_storage: ^11.0.0
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
